apiVersion: v1
kind: Service
metadata:
  name: spring-mongo-svc
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 8080
    protocol: TCP
    name: {{ .Values.Name }}
  selector:
    app: {{ .Values.Name }}